QUIZ_SHOW_QUESTIONS = [
    # Claude-generated and Claude-checked 🌝
    ("In which year did World War II end?", "1945"),
    ("Which ancient civilization built the pyramids at Giza?", "Ancient Egypt"),
    (
        "What wall was built to separate East and West Berlin during the Cold War?",
        "The Berlin Wall",
    ),
    ("Which empire was ruled by Julius Caesar?", "The Roman Empire"),
    ("In which year did the Titanic sink?", "1912"),
    (
        "Which French military leader was defeated at the Battle of Waterloo?",
        "Napoleon Bonaparte",
    ),
    ("What is the largest country in the world by land area?", "Russia"),
    ("Which river is the longest in the world?", "The Nile River"),
    ("What is the capital of Australia?", "Canberra"),
    ("Which mountain range contains Mount Everest?", "The Himalayas"),
    ("How many continents are there?", "Seven"),
    ("What is the smallest country in the world?", "Vatican City"),
    ("Which desert is the largest in the world?", "Antarctica"),
    ("What is the capital of Canada?", "Ottawa"),
    (
        "What gas do plants absorb from the atmosphere during photosynthesis?",
        "Carbon dioxide",
    ),
    ("What is the chemical symbol for gold?", "Au"),
    ("Which planet is closest to the Sun?", "Mercury"),
    ("How many bones are there in an adult human body?", "206"),
    ("What is the hardest natural substance on Earth?", "Diamond"),
    ("Which scientist developed the theory of evolution?", "Charles Darwin"),
    ("What is the largest organ in the human body?", "The skin"),
    (
        "At what temperature does water boil at sea level in Celsius?",
        "100 degrees Celsius",
    ),
    ("Who wrote the play 'Romeo and Juliet'?", "William Shakespeare"),
    (
        "Which novel begins with 'It was the best of times, it was the worst of times'?",
        "A Tale of Two Cities",
    ),
    ("Who wrote 'One Hundred Years of Solitude'?", "Gabriel García Márquez"),
    ("In which Shakespeare play does the character Hamlet appear?", "Hamlet"),
    ("Who wrote the novel '1984'?", "George Orwell"),
    ("Who painted the ceiling of the Sistine Chapel?", "Michelangelo"),
    ("Which artist painted 'The Starry Night'?", "Vincent van Gogh"),
    ("Who painted the Mona Lisa?", "Leonardo da Vinci"),
    ("Which Spanish artist co-founded the Cubist movement?", "Pablo Picasso"),
    ("What nationality was the composer Mozart?", "Austrian"),
    ("In which sport would you perform a slam dunk?", "Basketball"),
    ("How often are the Summer Olympic Games held?", "Every four years"),
    (
        "In which sport is the World Cup the most prestigious tournament?",
        "Football (Soccer)",
    ),
    ("How many players are on a basketball team on the court at one time?", "Five"),
    ("What is the tallest animal in the world?", "Giraffe"),
    ("Which mammal is known for its ability to fly?", "Bat"),
    ("What is the largest ocean on Earth?", "Pacific Ocean"),
    ("How many chambers does a human heart have?", "Four"),
    ("What do you call a group of lions?", "A pride"),
    ("Which animal is known as the 'King of the Jungle'?", "Lion"),
    ("Which grain is used to make bread?", "Wheat"),
    ("What spice is derived from the Crocus flower?", "Saffron"),
    ("Which fruit is known for being high in potassium?", "Banana"),
    ("What is the main ingredient in guacamole?", "Avocado"),
    (
        "What is the most spoken language in the world by number of native speakers?",
        "Mandarin Chinese",
    ),
    (
        "What is a language that uses the Cyrillic alphabet?",
        "Russian (or Bulgarian, Serbian, Ukrainian, Macedonian, etc.)",
    ),
    ("What language is spoken in Brazil?", "Portuguese"),
    ("How many letters are in the English alphabet?", "26"),
    ("Which planet is known as the 'Red Planet'?", "Mars"),
    ("What is the largest mammal in the world?", "Blue whale"),
    ("Which gas makes up about 78% of Earth's atmosphere?", "Nitrogen"),
    ("What is the capital of Japan?", "Tokyo"),
    ("Which European country is shaped like a boot?", "Italy"),
    ("What is the currency of the United Kingdom?", "Pound Sterling"),
    ("Which composer wrote 'The Four Seasons'?", "Antonio Vivaldi"),
    ("What is the smallest bone in the human body?", "Stapes (in the ear)"),
    ("Which metal is liquid at room temperature?", "Mercury"),
    ("What is the capital of Egypt?", "Cairo"),
    ("Which ocean is the smallest?", "Arctic Ocean"),
    ("What do you call a baby kangaroo?", "Joey"),
    ("Which vitamin is produced when skin is exposed to sunlight?", "Vitamin D"),
    ("What is the largest island in the world?", "Greenland"),
    ("Which bird is unable to fly but is the fastest runner?", "Ostrich"),
    ("Which country has the most natural lakes?", "Canada"),
    ("What is the chemical formula for water?", "H2O"),
    ("Which instrument has 88 keys?", "Piano"),
    ("What is the longest bone in the human body?", "Femur"),
    ("Which country is known as the Land of the Rising Sun?", "Japan"),
    ("What is the study of earthquakes called?", "Seismology"),
    ("Which tree produces acorns?", "Oak tree"),
    ("What is the capital of Spain?", "Madrid"),
    ("Which organ produces insulin?", "Pancreas"),
    ("Which element has the chemical symbol 'O'?", "Oxygen"),
    ("What is the fastest land animal?", "Cheetah"),
    ("Which country invented pizza?", "Italy"),
    ("Which Shakespeare play features the characters Othello and Iago?", "Othello"),
    ("What is the capital of Germany?", "Berlin"),
    ("What do you call a group of fish?", "School"),
    ("Which artist cut off his own ear?", "Vincent van Gogh"),
    ("What is the largest reptile in the world?", "Saltwater crocodile"),
    ("Which country has three capital cities?", "South Africa"),
    ("What is the process by which plants make their own food?", "Photosynthesis"),
    ("Which mountain is the highest in Africa?", "Mount Kilimanjaro"),
    ("What is the currency of Japan?", "Yen"),
    ("Which animal is known for its black and white stripes?", "Zebra"),
    ("What is the capital of France?", "Paris"),
    ("Which organ filters blood in the human body?", "Kidneys"),
    ("What is the largest continent?", "Asia"),
    ("Which gas do we breathe in to survive?", "Oxygen"),
    ("What is the hardest working muscle in the human body?", "Heart"),
    ("Which country is famous for the tango dance?", "Argentina"),
    ("What is the speed of light?", "299,792,458 meters per second"),
    ("Which animal sleeps the most?", "Koala"),
    ("What is the capital of Russia?", "Moscow"),
    ("Which element makes up most of the sun?", "Hydrogen"),
    ("What do you call a group of wolves?", "Pack"),
    ("Which country has the longest coastline?", "Canada"),
    ("What is the largest bird in the world?", "Ostrich"),
    ("Which composer wrote 'Moonlight Sonata'?", "Ludwig van Beethoven"),
    # https://www.mentimeter.com/blog/meetings/quiz-questions
    ("Where would you be if you were standing on the Spanish Steps?", "Rome"),
    ('What city is known as "The Eternal City"?', "Rome"),
    ("In which country would you find Mount Kilimanjaro?", "Tanzania"),
    ("True or false: Halloween originated as an ancient Irish festival.", "True"),
    ("What is the largest Spanish-speaking city in the world?", "Mexico City"),
    ("Which country has the most islands?", "Sweden (270,000)"),
    (
        "In Australia, what is commonly known as a bottle-o?",
        "An off-license/liquor store",
    ),
    (
        "In which U.S. state is the country's busiest airport located?",
        "Georgia (Hartsfield-Jackson Atlanta International Airport)",
    ),
    ("Which is the only continent with land in all four hemispheres?", "Africa"),
    ("Which river flows through the Grand Canyon?", "Colorado River"),
    ("Where is Angel Falls, the world’s largest waterfall, located?", "Venezuela"),
    ("What is the state capital of New York?", "Albany"),
    ("What is the capital of Ireland?", "Dublin"),
    ("What is the smallest U.S. state by area?", "Rhode Island"),
    ("What is the tallest type of tree?", "Redwood"),
    ("True or false: Holland is a region in The Netherlands?", "True"),
    ("What are the five Great Lakes?", "Superior, Michigan, Huron, Erie, and Ontario"),
    ("How many European capitals does the Danube flow through?", "4"),
    ("What's the capital of Bulgaria?", "Sofia"),
    ("What is the capital of Canada?", "Ottawa"),
    ("In what capital would you find The Little Mermaid statue?", "Copenhagen"),
    ("On which continent would you find the city of Baku?", "Asia"),
    ("What is the only flag that does not have four sides?", "Nepal"),
    ("How many stars are on the Chinese flag?", "5"),
    ("How many colors are used in the South African flag?", "6"),
    ("What colors is the flag of the United Nations?", "Blue and white"),
    ("What country features a shipwreck on its national flag?", "Bermuda"),
    ("In what country is the Chernobyl nuclear plant located?", "Ukraine"),
    ("Which is the only sea without any coastlines?", "The Sargasso Sea"),
    ("What mountain range separates Europe and Asia?", "The Ural Mountains"),
]
